version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: imran-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: imran-app-1
    depends_on:
      - db
    command: ["java", "-jar", "target/seMethods-0.1.0.2-jar-with-dependencies.jar"]