name: Coursework CI
on: push

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run unit tests
        run: mvn -Dtest=Coursework.AppTest,Coursework.ReportManagerTest test

  IntegrationTests:
    name: Integration Tests (world-db)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build DB image
        run: docker build -t worlddb ./db

      - name: Run DB container
        run: docker run -d --name world-db -p 33060:3306 worlddb

      - name: Run integration tests
        run: mvn -Dtest=Coursework.AppIntegrationTest,Coursework.ReportGenerationTest test

      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./target/site/jacoco
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Stop & clean DB container
        if: always()
        run: |
          docker stop world-db
          docker rm world-db
          docker image rm worlddb

  BuildCompose:
    name: Build app with docker-compose
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # build the JAR first
      - name: Package app
        run: mvn -B -DskipTests package

      # confirm JAR exists before docker build
      - name: Verify JAR built
        run: ls -lh target/

    
      - name: Allow target folder in Docker context
        run: |
          echo "!target/*.jar" >> .dockerignore

      # bring up containers
      - name: Compose up (exit when app exits)
        run: docker compose up --abort-on-container-exit --build

  AutoGenerateReports:
    name: Generate and Upload Reports
    runs-on: ubuntu-22.04
    needs: [BuildCompose]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run app to generate reports
        run: |
          mvn package -DskipTests
          echo "!target/*.jar" >> .dockerignore
          docker compose up --abort-on-container-exit --build

      - name: Upload Generated Reports
        uses: actions/upload-artifact@v4
        with:
          name: Generated_Reports
          path: src/main/resources/reports/
