name: Coursework CI
on: push
permissions:
  contents: write


jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run unit tests
        run: mvn -Dtest=Coursework.AppTest,Coursework.ReportManagerTest test

  IntegrationTests:
    name: Integration Tests (world-db)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Spin up the world DB container from your db/ folder
      - name: Build DB image
        run: docker build -t worlddb ./db
      - name: Run DB container
        run: docker run -d --name world-db -p 33060:3306 worlddb

      - name: Run integration tests
        run: mvn -Dtest=Coursework.AppIntegrationTest,Coursework.ReportGenerationTest test


      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./target/site/jacoco
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Stop & clean DB container
        if: always()
        run: |
          docker stop world-db
          docker rm world-db
          docker image rm worlddb

  BuildCompose:
    name: Build app with docker-compose
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Package app
        run: mvn package -DskipTests
      - name: Compose up (exit when app exits)
        run: docker compose up --abort-on-container-exit
      - name: Publish Release (master only)
        if: github.ref == 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar


  AutoGenerateReports:
    name: Generate and Upload Reports
    runs-on: ubuntu-22.04
    needs: [BuildCompose]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run app to generate reports
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit --build

      - name: Upload Generated Reports
        uses: actions/upload-artifact@v4
        with:
          name: Generated_Reports
          path: src/main/resources/reports/
